MonitoringStation_Hallway3_Text_BlueDoorGone::
	.string "The BLUE KEY unlocked the door!$"
	
MonitoringStation_Hallway3_Text_YellowDoorGone::
	.string "The YELLOW KEY unlocked the door!$"

MonitoringStation_Hallway3_Text_Door::
	.string "This door is electronically locked.\n"
	.string "A specific keycard can unlock it.$"

MonitoringStation_Hallway3_Text_AdminTalk::
	.string "Look, I'm sorry for causing all\n"
	.string "this trouble.\p"
	.string "I hope I managed to right my wrongs\n"
	.string "by helping you out.\p"
	.string "While being ambushed by the monster,\n"
	.string "I realized it looked a lot like a\p"
	.string "KABUTOPS.\p"
	.string "Going by the information I heard from\n"
	.string "the GRUNT who accompanied me,\p"
	.string "I concluded that the monster is\n"
	.string "a unique, GHOST-type version of\p"
	.string "a KABUTOPS.\p"
	.string "It seems to be gone now, but maybe\n"
	.string "there is more to this…\p"
	.string "Anyway, let's go.$"