Pokecenter_Text_NoHope::
	.string "THERE IS NO HOPE OF ESCAPE$"
	
Pokecenter_Text_Pointless::
	.string "IT IS POINTLESS TO TRY$"
	
Pokecenter_Text_BeyondReach::
	.string "THE END IS BEYOND REACH$"
	
Pokecenter_Text_DontGiveUp::
	.string "YOU DON'T GIVE UP, DO YOU$"
	
Pokecenter_Text_KeepTrying::
	.string "WHY DO YOU KEEP TRYING$"
	
Pokecenter_Text_Determination::
	.string "I ADMIRE YOUR DETERMINATION$"
	
Pokecenter_Text_AlmostThere::
	.string "YOU ALMOST MADE IT$"
	
Pokecenter_Text_TheEnd::
	.string "WITH YOUR COURAGE AND PERSEVERANCE\n"
	.string "YOU OVERCAME MY ILLUSION\p"
	.string "I WILL HAVE TO TRY SOMETHING ELSE$"