VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish:: @ 8193EC1
    .string "I'm the FISHING GURU!\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"

VermilionCity_House1_Text_TakeThisAndFish:: @ 8193F2A
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru:: @ 8193F81
    .string "{PLAYER} received an OLD ROD from\n"
    .string "the FISHING GURU.$"

VermilionCity_House1_Text_FishingIsAWayOfLife:: @ 8193FAF
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "From the seas to rivers, go out\n"
    .string "and land the big one, my friend.$"

VermilionCity_House1_Text_OhThatsSoDisappointing:: @ 8194028
    .string "Oh…\n"
    .string "That's so disappointing…$"

VermilionCity_House1_Text_HowAreTheFishBiting:: @ 8194045
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"

VermilionCity_House1_Text_NoRoomForNiceGift:: @ 819406F
    .string "Oh, no!\p"
    .string "I had a nice gift for you, but you\n"
    .string "have no room for it!$"

Vermilion_House1_Text_DoYouLikeToFish:: @ 819918E
    .string "I'm the FISHING GURU's older\n"
    .string "brother.\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"

Vermilion_House1_Text_LikeYourStyleTakeThis:: @ 8199207
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"

Vermilion_House1_Text_ReceivedGoodRod:: @ 819925E
    .string "{PLAYER} received a GOOD ROD from\n"
    .string "the FISHING GURU's brother.$"

Vermilion_House1_Text_GoodRodCanCatchBetterMons:: @ 8199296
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "A crummy OLD ROD could only catch\n"
    .string "MAGIKARP, yes?\p"
    .string "But with a GOOD ROD, you can\n"
    .string "catch much better POKéMON.$"

Vermilion_House1_Text_OhThatsDisappointing:: @ 8199337
    .string "Oh…\n"
    .string "That's so disappointing…$"

Vermilion_House1_Text_HowAreTheFishBiting:: @ 8199354
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"

Vermilion_House1_Text_YouHaveNoRoomForGift:: @ 819937E
    .string "Oh, no!\p"
    .string "I had a gift for you, but you have\n"
    .string "no room for it!$"

