MonitoringStation_Central_Text_GreyDoor::
	.string "The power outage has activated the\n"
	.string "emergency doors.$"

MonitoringStation_Central_Text_RocketAttack::
	.string "MACHOKE!\n"
	.string "Use VITAL THROW!!$"
	
MonitoringStation_Central_Text_MachokeNoise::
	.string "MACHOKE: Gwoooh!$"
	
MonitoringStation_Central_Text_RocketWhat::
	.string "W-what??!$"
	
MonitoringStation_Central_Text_RocketNo::
	.string "N-no! Wait, NO!!$"
	
MonitoringStation_Central_Text_RocketOh::
	.string "Huh? It went… r-right through me?$"
	
MonitoringStation_Central_Text_RocketAh::
	.string "Waaaaaaaaaaaaaaaaaaahh!!!$"

MonitoringStation_Central_Text_Admin::
	.string "A… child?\n"
	.string "This day can't get any stranger.\p"
	.string "You want my RED KEY, right?\p"
	.string "Well, unfortunately, I no longer\n"
	.string "have it.\p"
	.string "It was taken from me by the ghost\n"
	.string "you have probably seen wandering\p"
	.string "around.\p"
	.string "I suggest you try to find our\n"
	.string "EXECUTIVE instead. He has the\p"
	.string "other key in his possession.\p"
	.string "The alternative would be to\n"
	.string "challenge that monster…\p"
	.string "I suggest you search for a way to\n"
	.string "get into the EXECUTIVE's office.$"

MonitoringStation_Central_Text_Admin2::
	.string "Well, what are you waiting for?$"
	
MonitoringStation_Central_Text_StorageGrunt1::
	.string "Hey!\n"
	.string "How's it going?\p"
	.string "It's me, the GRUNT you met at\n"
	.string "the storage room!\p"
	.string "You're wondering why I am\n"
	.string "standing here?\p"
	.string "Well… um… that's a secret!\p"
	.string "Maybe you will find out at\n"
	.string "some point.\p"
	.string "Well, good luck finding that\n"
	.string "YELLOW KEY!$"