MonitoringStation_Central_Text_GreyDoor::
	.string "The power outage has activated the\n"
	.string "emergency doors.$"

MonitoringStation_Central_Text_RocketAttack::
	.string "MACHOKE!\n"
	.string "Use VITAL THROW!!$"
	
MonitoringStation_Central_Text_MachokeNoise::
	.string "MACHOKE: Gwoooh!$"
	
MonitoringStation_Central_Text_RocketWhat::
	.string "W-what??!$"
	
MonitoringStation_Central_Text_RocketNo::
	.string "N-no! Wait, NO!!$"
	
MonitoringStation_Central_Text_RocketOh::
	.string "Huh? It went… r-right through me?$"
	
MonitoringStation_Central_Text_RocketAh::
	.string "Waaaaaaaaaaaaaaaaaaahh!!!$"