MonitoringStation_Office_Text_BlockAdmin::
	.string "The exit is blocked by a strange\n"
	.string "force.$"
	
MonitoringStation_Office_Text_Admin::
	.string "Wait!!$"
	
MonitoringStation_Office_Text_AdminHelp::
	.string "I will help you.\p"
	.string "I can't just keep helping only\n"
	.string "myself.$"
	
MonitoringStation_Office_Text_AdminNo::
	.string "No!\n"
	.string "You stupid kid!\p"
	.string "It's a GHOST-type POKéMON!$"
	
MonitoringStation_Office_Text_AdminPokemon::
	.string "Go, DUSCLOPS!$"
	
MonitoringStation_Office_Text_AdminAttack::
	.string "Use SHADOW PUNCH!!$"
	
MonitoringStation_Office_Text_AdminComeBack::
	.string "DUSCLOPS! Come back!$"
	
MonitoringStation_Office_Text_AdminKey::
	.string "… Go pick up that RED KEY.\p"
	.string "It's right there, on the desk.$"
	
MonitoringStation_Office_Text_Talk::
	.string "I will need a long rest after\n"
	.string "all this commotion.$"
	
MonitoringStation_Office_Text_NotDone::
	.string "You really shouldn't be playing\n"
	.string "around at a time like this.\p"
	.string "Go pick up that RED KEY.$"
	
MonitoringStation_Office_Text_Done::
	.string "Okay, let's go.$"