MonitoringStation_Office_Text_BlockAdmin::
	.string "The exit is blocked by a strange\n"
	.string "force.$"
	
MonitoringStation_Office_Text_Admin::
	.string "Wait!!$"
	
MonitoringStation_Office_Text_AdminHelp::
	.string "I will help you.\p"
	.string "I can't just keep helping only\n"
	.string "myself.$"
	
MonitoringStation_Office_Text_AdminNo::
	.string "No!\n"
	.string "You stupid kid!\p"
	.string "It's a GHOST-type POKéMON!$"