MonitoringStation_Office_Text_BlockAdmin::
	.string "The exit is blocked by a strange\n"
	.string "force.$"
	
MonitoringStation_Office_Text_Admin::
	.string "Wait!!$"
	
MonitoringStation_Office_Text_AdminHelp::
	.string "I will help you.\p"
	.string "I can't just keep helping only\n"
	.string "myself.$"
	
MonitoringStation_Office_Text_AdminNo::
	.string "No!\n"
	.string "You stupid kid!\p"
	.string "It's a GHOST-type POKéMON!$"
	
MonitoringStation_Office_Text_AdminPokemon::
	.string "Go, DUSCLOPS!$"
	
MonitoringStation_Office_Text_AdminAttack::
	.string "Use SHADOW PUNCH!!$"
	
MonitoringStation_Office_Text_AdminComeBack::
	.string "DUSCLOPS! Come back!$"
	
MonitoringStation_Office_Text_AdminKey::
	.string "… Go pick up that RED KEY.\p"
	.string "It's right there, on the desk.$"
	
MonitoringStation_Office_Text_Talk::
	.string "Yeah, I'm sorry for causing all\n"
	.string "this trouble.\p"
	.string "I hope I managed to right my wrongs\n"
	.string "by helping you out.\p"
	.string "While being ambushed by the monster,\n"
	.string "I realized it looked a lot like a\p"
	.string "KABUTOPS.\p"
	.string "Going by the information I heard from\n"
	.string "the GRUNT who accompanied me,\p"
	.string "I concluded that the monster is\n"
	.string "a unique, GHOST-type version of\p"
	.string "a KABUTOPS.\p"
	.string "It seems to be gone now, but maybe\n"
	.string "there is more to this…$"
	
MonitoringStation_Office_Text_NotDone::
	.string "You really shouldn't be playing\n"
	.string "around at a time like this.\p"
	.string "Go pick up that RED KEY.$"
	
MonitoringStation_Office_Text_Done::
	.string "Okay, let's go.$"