MonitoringStation_Quarters_Text_Funny::
	.string "Still here?!\p"
	.string "Wait…\n"
	.string "Everyone else left the base?!\p"
	.string "Ahh, finally I will have some peace\n"
	.string "and quiet around here!$"

MonitoringStation_Quarters_Text_RocketM1::
	.string "Can't you stop bothering me?\n"
	.string "I'm watching TV!$"
	
MonitoringStation_Quarters_Text_RocketM2::
	.string "Stress always makes me hungry.\p"
	.string "I hope they still got something\n"
	.string "good in here…$"
	
MonitoringStation_Quarters_Text_RocketM3::
	.string "You're looking for a YELLOW KEY?\p"
	.string "The EXECUTIVE is still hiding away,\n"
	.string "so you should go find our ADMIN.\p"
	.string "You must have ran into our her\n"
	.string "somewhere along the way.\p"
	.string "The ADMIN is supposed to have a\n"
	.string "YELLOW KEY on her.\p"
	.string "…… …… …… ……\p"
	.string "If she didn't mention it whatsoever,\n"
	.string "she must be hiding something…\p"
	.string "Maybe we should go talk to her…\p"
	.string "… A boulder is blocking the way to\n"
	.string "the entrance hallway?\p"
	.string "Then she must have locked herself\n"
	.string "in there.\p"
	.string "We will need a strong POKéMON to\n"
	.string "take care of that boulder.\p"
	.string "Since your POKéMON are too afraid\n"
	.string "to function properly… Hmm…\p"
	.string "I recall there being a KANGASKHAN\n"
	.string "in the holding room.\p"
	.string "That one would be perfect for\n"
	.string "our little plan.\p"
	.string "If you go free that caged POKéMON,\n"
	.string "I can command it to use STRENGTH\p"
	.string "against that boulder.$"
	
MonitoringStation_Quarters_Text_RocketM3Again::
	.string "If you haven't freed KANGASKHAN\n"
	.string "yet, go do that now please.\p"
	.string "I want to get to the bottom of this\n"
	.string "scheme of our esteemed ADMIN…$"
	
MonitoringStation_Quarters_Text_RocketM3Solution::
	.string "You've been to the holding room?\n"
	.string "And you didn't find KANGASKHAN?\p"
	.string "Ugh, I'll just go free it myself.\n"
	.string "Meet me at the monitoring office.$"
	
MonitoringStation_Quarters_Text_RocketM4::
	.string "Why did you open the door?!\p"
	.string "Now, that monster can get in here\n"
	.string "anytime it wants to!$"
	
MonitoringStation_Quarters_Text_RocketF1::
	.string "Shhht!\p"
	.string "Can't you see that I'm hiding,\n"
	.string "you little twerp?$"
	
MonitoringStation_Quarters_Text_RocketF2::
	.string "Some people claim that our ADMIN\n"
	.string "has been plotting to take over\p"
	.string "the position of SEVII's EXECUTIVE.$"
	