MonitoringStation_Quarters_Text_RocketM1::
	.string "Can't you stop bothering me?\n"
	.string "I'm watching TV!$"
	
MonitoringStation_Quarters_Text_RocketM2::
	.string "Stress always makes me hungry.\p"
	.string "I hope they still got something\n"
	.string "good in here…$"
	
MonitoringStation_Quarters_Text_RocketM3::
	.string "You're looking for a YELLOW KEY?\p"
	.string "The EXECUTIVE is still hiding away,\n"
	.string "so you should go find our ADMIN.\p"
	.string "What's that? You've already\n"
	.string "met her before?\p"
	.string "… … … …\p"
	.string "The ADMIN is supposed to have a\n"
	.string "YELLOW KEY on her.\p"
	.string "If she didn't mention it whatsoever,\n"
	.string "she must be hiding something…\p"
	.string "She is probably in the entrance\n"
	.string "hallway at the moment.\p"
	.string "Maybe we should go talk to her…\p"
	.string "In order to destroy that boulder\n"
	.string "blocking access to the hallway,\p"
	.string "we will need a strong POKéMON.\p"
	.string "I recall there being a VENUSAUR\n"
	.string "in the holding room.\p"
	.string "That one would be perfect for\n"
	.string "our little plan.\p"
	.string "If you go free that caged VENUSAUR,\n"
	.string "I can command it to use STRENGTH\p"
	.string "against that boulder.$"
	
MonitoringStation_Quarters_Text_RocketM3Again::
	.string "If you haven't freed the VENUSAUR\n"
	.string "yet, go do that now please.\p"
	.string "I want to get to the bottom of this\n"
	.string "scheme of our esteemed ADMIN…$"
	
MonitoringStation_Quarters_Text_RocketM3Solution::
	.string "You've been to the holding room?\n"
	.string "And you could not find VENUSAUR?\p"
	.string "Ugh, I'll just go free it myself.\n"
	.string "Meet me at the monitoring office.$"
	
MonitoringStation_Quarters_Text_RocketM4::
	.string "Why did you open the door?!\p"
	.string "Now, that monster can get in here\n"
	.string "anytime it wants to!$"
	
MonitoringStation_Quarters_Text_RocketF1::
	.string "Shhht!\p"
	.string "Can't you see that I'm hiding,\n"
	.string "you little twerp?$"
	
MonitoringStation_Quarters_Text_RocketF2::
	.string "Some people claim that our ADMIN\n"
	.string "has been plotting to take over\p"
	.string "the position of SEVII's EXECUTIVE.$"
	