MonitoringStation_ConferenceRoom_Text_RocketM1::
	.string "Yeah, we were notified that\n"
	.string "you had somehow snuck your\p"
	.string "way in.\p"
	.string "The pipsqueak you saw near\n"
	.string "the elevator is right there,\p"
	.string "cowering behind the sofa.\p"
	.string "He ran in here the moment the\n"
	.string "emergency doors reopened.\p"
	.string "Hahaha, Poor guy.$"

MonitoringStation_ConferenceRoom_Text_RocketM2::
	.string "Right now, I don't feel like\n"
	.string "talking to some stuck-up kid.\p"
	.string "Go find someone else to bother!$"

MonitoringStation_ConferenceRoom_Text_RocketM3::
	.string "Hm? You're looking for a way\n"
	.string "to get inside the office of\p"
	.string "the EXECUTIVE?\p"
	.string "You will need a YELLOW KEY\n"
	.string "for that.\p"
	.string "Do I look important enough\n"
	.string "for you to think I carry\n"
	.string "around things like that?\p"
	.string "I don't have a YELLOW KEY,\n"
	.string "but I got a BLUE KEY.\p"
	.string "It will help you find more\n"
	.string "GRUNTS that can help you.$"
	
ConferenceRoom_Text_ObtainedBlueKey::
	.string "{PLAYER} received a BLUE KEY\n"
	.string "from the TEAM ROCKET GRUNT!$"

MonitoringStation_ConferenceRoom_Text_RocketM32::
	.string "I hope you manage to reach the\n"
	.string "EXECUTIVE without getting into\p"
	.string "trouble.$"

MonitoringStation_ConferenceRoom_Text_RocketF1::
	.string "If that monster dares to set\n"
	.string "a foot inside this room, it\p"
	.string "will have to contend with my\n"
	.string "powerful POKéMON…\n"

MonitoringStation_ConferenceRoom_Text_RocketF2::
	.string "I'm s-so n-n-nervous!\n"
	.string "Are we even going to survive\p"
	.string "i-in here…?$"

MonitoringStation_ConferenceRoom_Text_Scientist1::
	.string "SIGH…\p"
	.string "I warned them, you know.\p"
	.string "They should have left that\n"
	.string "EMERALD inside that cave.\p"
	.string "They should never have opened\n"
	.string "that cavern in the first\p"
	.string "place. That EMERALD turned out to\n"
	.string "to be completely useless anyway.$"

MonitoringStation_ConferenceRoom_Text_Scientist2::
	.string "I'm looking for a way to subdue\n"
	.string "that thing.\p"
	.string "But so far, I've found nothing of\n"
	.string "any use…$"

MonitoringStation_ConferenceRoom_Text_Text::
	.string "Diary: Sept. 16\n"
    .string "The Dig\p"
	.string "Shortly after this base was built,\n"
	.string "massive energy readings were picked\p"
	.string "up by our radar technology.\p"
	.string "The readings came from even further\n"
	.string "below ground.\p"
	.string "We ended up digging our way into a\n"
	.string "small cavern, where we found\p"
	.string "a large gemstone made entirely\n"
	.string "of EMERALD.\p"
	.string "It was clear the readings came\n"
	.string "from this particular stone.\p"
	.string "Despite some skepticism among\n"
	.string "the research team, our\p"
	.string "EXECUTIVE ordered the stone to be\n"
	.string "taken and subjected to rigorous\p"
	.string "testing.\p"
	.string "Unfortunately, initial tests failed\n"
	.string "to unlock the powers hidden within\p"
	.string "the EMERALD…$"

	.string "This day can't get any stranger.\p"