MonitoringStation_ConferenceRoom_Text_RocketM1::
	.string "Yeah, we were notified that\n"
	.string "you had somehow snuck your\p"
	.string "way in.\p"
	.string "The pipsqueak you saw near\n"
	.string "the elevator is right there,\p"
	.string "trying to reach his family.\p"
	.string "He ran in here the moment the\n"
	.string "emergency doors reopened.\p"
	.string "Hahaha, Poor guy.$"

MonitoringStation_ConferenceRoom_Text_RocketM2::
	.string "Right now, I don't feel like talking\n"
	.string "to some stuck-up kid.\p"
	.string "Go find someone else to bother!$"

MonitoringStation_ConferenceRoom_Text_RocketM3::
	.string "Hm? You're looking for a way to\n"
	.string "get inside the office of\p"
	.string "the EXECUTIVE?\p"
	.string "You will need a YELLOW KEY\n"
	.string "for that.\p"
	.string "Do I look important enough for you\n"
	.string "to think I carry around things\p"
	.string "like that?\p"
	.string "I don't have a YELLOW KEY,\n"
	.string "but I got a BLUE KEY.\p"
	.string "It will help you access more rooms\n"
	.string "within this complex.$"
	
MonitoringStation_ConferenceRoom_Text_ObtainedBlueKey::
	.string "{PLAYER} received a BLUE KEY\n"
	.string "from the TEAM ROCKET GRUNT!$"

MonitoringStation_ConferenceRoom_Text_RocketM32::
	.string "I hope you manage to reach the\n"
	.string "EXECUTIVE without running\p"
	.string "into trouble.$"

MonitoringStation_ConferenceRoom_Text_RocketF1::
	.string "If that monster dares to set\n"
	.string "a foot inside this room, it\p"
	.string "will have to contend with my\n"
	.string "powerful POKéMON…\n"

MonitoringStation_ConferenceRoom_Text_RocketF2::
	.string "I'm s-so n-n-nervous!\p"
	.string "Are we even going to survive\p"
	.string "i-in here…?$"

MonitoringStation_ConferenceRoom_Text_Scientist1::
	.string "SIGH…\p"
	.string "I warned them, you know.\p"
	.string "They should have left that EMERALD\n"
	.string "inside that cave.\p"
	.string "They should never have opened that\n"
	.string "cavern in the first place.\p"
	.string "That EMERALD turned out to be\n"
	.string "completely useless anyway.$"

MonitoringStation_ConferenceRoom_Text_Scientist2::
	.string "I'm looking for a way to subdue\n"
	.string "that thing.\p"
	.string "But so far, I've found nothing of\n"
	.string "any use…$"

MonitoringStation_ConferenceRoom_Text_Text::
	.string "Diary: Sept. 16\n"
    .string "The Dig\p"
	.string "Shortly after this base was built,\n"
	.string "large energy readings were picked\p"
	.string "up by our radar technology.\p"
	.string "The readings came from even further\n"
	.string "below ground.\p"
	.string "We ended up digging our way into a\n"
	.string "small cavern, where we found a\p"
	.string "large green gemstone:\n"
	.string "the EMERALD.\p"
	.string "It was clear the readings came\n"
	.string "from this particular stone.\p"
	.string "Despite some skepticism among the\n"
	.string "research team, our EXECUTIVE\p"
	.string "ordered the stone to be taken\n"
	.string "and subjected to rigorous\p"
	.string "testing.\p"
	.string "Unfortunately, initial tests failed\n"
	.string "to unlock the powers hidden within\p"
	.string "the EMERALD…$"

MonitoringStation_ConferenceRoom_Text_RocketM4::
	.string "Please, just answer the darn phone!\n"
	.string "Why is it always me?!$"