MonitoringStation_Text_Admin::
	.string "…… … that door coming along?\n"
	.string "We haven't got all day!$"
	
MonitoringStation_Text_StorageGrunt::
	.string "This stuff takes time! Without a key,\n"
	.string "I need to manually override the lock.\p"
	.string "You could have just helped that kid\n"
	.string "get to the EXECUTIVE by giving that\p"
	.string "YELLOW KEY…$"
	
MonitoringStation_Text_Quartet::
	.string "Hold it!\n"
	.string "You guys got some explaining to do.$"
	
MonitoringStation_Text_Admin2::
	.string "And who are you to order me around?\p"
	.string "I will report your misbehavior to\n"
	.string "the EXECUTIVE.\p"
	.string "You can explain it to…$"
	
MonitoringStation_Text_Executive::
	.string "I AM the EXECUTIVE, you nitwit!\p"
	.string "I've been undercover as a GRUNT for\n"
	.string "a while now, in order to reveal\p"
	.string "your scheme to overthrow me.$"
	
MonitoringStation_Text_StorageGrunt2::
	.string "Uh-oh…$"
	
MonitoringStation_Text_Executive2::
	.string "And now, you can explain to me why\n"
	.string "you wanted to leave me, and so\p"
	.string "many GRUNTS, behind.$"
	
MonitoringStation_Text_Admin3::
	.string "Alright then. I wanted to be the\n"
	.string "EXECUTIVE, now what?$"
	
MonitoringStation_Text_Executive3::
	.string "It's not just that…\p"
	.string "You were willing to leave everyone\n"
	.string "behind just to accomplish that.\p"
	.string "You wanted to sacrifice all your\n"
	.string "colleagues to a monster to get\p"
	.string "what you want.\p"
	.string "You aren't worthy of the rank of\n"
	.string "ADMIN, let alone of the rank of\p"
	.string "EXECUTIVE.$"
	
MonitoringStation_Text_TookYellowKey::
	.string "The EXECUTIVE took the YELLOW KEY\n"
	.string "from the ADMIN.$"
	
MonitoringStation_Text_Executive4::
	.string "I think you need this more than\p"
	.string "she ever will…\p"
	.string "My RED KEY is on my desk in my\n"
	.string "personal office.\p"
	.string "You can use it to open this door\n"
	.string "in a second, rather than taking\p"
	.string "hours like these buffoons.$"
	
MonitoringStation_Text_ObtainedYellowKey::
	.string "{PLAYER} received a YELLOW KEY\n"
	.string "from the EXECUTIVE!$"
	
MonitoringStation_Text_Executive5::
	.string "She let you run around, searching\n"
	.string "for this key in vain.\p"
	.string "Just so the monster would not go\n"
	.string "after this sneaky duo instead.\p"
	.string "Yes, you were set up to be a big\n"
	.string "distraction for that beast.\p"
	.string "But now, you have a valid reason to\n"
	.string "go out there one more time.\p"
	.string "You go get that RED KEY.$"
	
MonitoringStation_Text_StorageGruntLoose::
	.string "I got nothing to do with it!\n"
	.string "I swear!$"
	
MonitoringStation_Text_AdminLoose::
	.string "I might have gone too far\n"
	.string "with this…$"
	
MonitoringStation_Text_ExecutiveIntro::
	.string "Aah, that's much better.\n"
	.string "That GRUNT outfit is so very\p"
	.string "uncomfortable.$"
	
MonitoringStation_Text_ExecutiveKey::
	.string "Did you manage to get your hands on\n"
	.string "the RED KEY?$"
	
MonitoringStation_Text_ExecutiveYay::
	.string "FUCKING AWESOME!\n"
	.string "TO BE CONTINUED!$"
	
MonitoringStation_Text_ExecutiveAww::
	.string "Please go get that key quickly.\n"
	.string "All of our lives depend on it.$"

MonitoringStation_Text_RedDoorGone::
	.string "The RED KEY unlocked the door!$"

MonitoringStation_Text_RedDoor::
	.string "This door is electronically locked.\n"
	.string "A specific keycard can unlock it.$"

MonitoringStation_Text_OutOfOrder::
	.string "The elevator seems to be out\n"
	.string "of order.$"

MonitoringStation_Text_RocketWhat::
	.string "What in tarnation are you doing\n"
    .string "here?!\p"
    .string "This place is off-limits to anyone\n"
    .string "but members of TEAM ROCKET!\p"
	.string "It's time to teach you a lesson!$"
	
MonitoringStation_Text_RocketAh::
	.string "What was that noise about?!$"
	
MonitoringStation_Text_RocketCheck::
	.string "I have to investigate.\p"
	.string "A POKéMON may have broken out of\n"
	.string "the containment area!\p"
	.string "You just stay put. I will be back\n"
	.string "in a jiffy.\p"
	.string "NO wandering around this base,\n"
	.string "understood?$"
	
MonitoringStation_Text_RocketNo::
	.string "AAAAAAAGHHHHHH!!!!$"