MonitoringStation_Text_RedDoorGone::
	.string "The RED KEY unlocked the door!$"

MonitoringStation_Text_RedDoor::
	.string "This door is electronically locked.\n"
	.string "A specific key can unlock it.$"

MonitoringStation_Text_OutOfOrder::
	.string "The elevator seems to be out\n"
	.string "of order.$"

MonitoringStation_Text_RocketWhat::
	.string "What in tarnation are you doing\n"
    .string "here?!\p"
    .string "This place is off-limits to anyone\n"
    .string "but members of TEAM ROCKET!\p"
	.string "It's time to teach you a lesson!$"
	
MonitoringStation_Text_RocketAh::
	.string "What was that noise about?!$"
	
MonitoringStation_Text_RocketCheck::
	.string "I have to investigate.\p"
	.string "A POKéMON may have broken out of\n"
	.string "the containment area!\p"
	.string "You just stay put. I will be back\n"
	.string "in a jiffy.\p"
	.string "NO wandering around this base,\n"
	.string "understood?$"
	
MonitoringStation_Text_RocketNo::
	.string "AAAAAAAGHHHHHH!!!!$"