MonitoringStation_Text_OutOfOrder::
	.string "The elevator seems to be out\n"
	.string "of order.$"

MonitoringStation_Text_RocketWhat::
	.string "What in tarnation are you doing\n"
    .string "here?!\p"
    .string "This place is off-limits to anyone\n"
    .string "but members of TEAM ROCKET!\p"
	.string "It's time to teach you a lesson!$"
	
MonitoringStation_Text_RocketAh::
	.string "What was that noise about?!$"
	
MonitoringStation_Text_RocketCheck::
	.string "I have no choice but to check whether\n"
	.string "some POKéMON escaped confinement.\p"
	.string "You just stay put. I will be back\n"
	.string "in a jiffy.\p"
	.string "NO wandering around this base,\n"
	.string "got it?$"
	
MonitoringStation_Text_RocketNo::
	.string "AAAAAAAGHHHHHH!!!!$"