CeruleanCity_House1_Text_Farm::
	.string "Hello there!\n"
	.string "I'm terribly sorry, but our BERRIES\n"
	.string "are specifically grown for folks\p"
	.string "who live on CINNABAR ISLAND.\p"
	.string "However, I could tell you about\n"
	.string "the history of our farm if you like.$"
	
CeruleanCity_House1_Text_FarmExplain::
	.string "This farm was built by our ancestors,\n"
	.string "who were the first to settle on what\p"
	.string "is now known as CINNABAR ISLAND.\p"
	.string "The fertile soil gave them the perfect\n"
	.string "opportunity to start growing BERRIES.\p"
	.string "The BERRIES turned out to be delicious,\n"
	.string "and soon, people started flocking to\p"
	.string "this island because of our farm.\p"
	.string "Eventually, folks began to settle,\n"
	.string "and this farm became the source of\p"
	.string "food for all of the islanders.\p"
	.string "To this day, the farm remains\n"
	.string "a family business.\p"
	.string "Although we don't sell BERRIES to\n"
	.string "outsiders, I want to show you my\p"
	.string "appreciation for your interest\n"
	.string "in this farm and its history.\p"
	.string "Here, take this.$"
	
CinnabarIsland_BerryFarm_Text_ObtainedLumBerry::
    .string "{PLAYER} received a LUM BERRY\n"
	.string "from the owner of the farm!$"
	
CinnabarIsland_BerryFarm_Text_Thanks::
    .string "I hope you enjoy your stay\n"
	.string "on CINNABAR ISLAND.$"
	
CinnabarIsland_BerryFarm_Text_Hello::
	.string "Hello, welcome to the\n"
	.string "CINNABAR BERRY FARM.\p"
	.string "Feel free to look around.$"
	
CinnabarIsland_BerryFarm_Text_Farm::
	.string "Hey there!\n"
	.string "I work the land, growing\n"
	.string "BERRY TREES and picking\p"
	.string "up the BERRIES that grow on them\n"
	.string "after they have dropped down.$"

CinnabarIsland_BerryFarm_Text_GiveJar::
	.string "Hey there!\n"
	.string "I work the land, growing\n"
	.string "BERRY TREES and picking\p"
	.string "up the BERRIES that grow on them\n"
	.string "after they have dropped down.$"
	.string "To give people a taste of what you\n"
	.string "you can do with BERRIES, we are\p"
	.string "giving away jars filled with\n"
	.string "BERRY POWDER for free.\p"
	.string "You can have one too!$"
	
CinnabarIsland_BerryFarm_Text_ObtainedBerryPowder::
    .string "{PLAYER} received the BERRY POWDER\n"
	.string "from the farm owner's son!$"
	
CinnabarIsland_BerryFarm_Text_Enjoy::
	.string "You can do a lot of things\n"
	.string "with BERRIES.\p"
	.string "For example, you can crush them\n"
	.string "into BERRY POWDER.\p"
	.string "You can then use BERRY POWDER to\n"
	.string "concote all sorts of medicine.\p"
	.string "Bet you didn't know that, huh?$"