MonitoringStation_Power_Text_Restore_Power::
	.string "Power has been restored.\p"
	.string "Emergency doors have been\n"
	.string "reopened.$"

MonitoringStation_Power_Text_Working::
	.string "The power in this base has\n"
	.string "been restored.$"
	
MonitoringStation_Power_Text_Rocket::
	.string "It's so dark in here…\p"
	.string "I must leave…\n"
	.string "before it swallows me…\p"
	.string "I MUST LEAVE!\p"
	.string "I MUST LEAVE!\p"
	.string "I MUST LEAVE NOW!\p"
	.string "LEAVE NOW!$"

MonitoringStation_Power_Text_Gym::
    .string "BASEMENT POKéMON GYM\n"
    .string "LEADER: ???\l"
    .string "TURN BACK.$"

MonitoringStation_Power_Text_Lance::
	.string "You may be CHAMPION…\p"
	.string "But you are still a failure…\p"
	.string "You will never become…\n"
	.string "A POKéMON MASTER…$"
	.string "Now go away…\p"
	.string "You have ruined me…$"
	
MonitoringStation_Power_Text_Honey1::
	.string "HOONEEEEEYYY!!!$"
	
MonitoringStation_Power_Text_Honey2::
	.string "I'VE BAKED A CAKE FOR YOU!!!$"

MonitoringStation_Power_Text_Mom::
	.string "IT'S YOU!!\p"
	.string "HAPPY BIRTHDAY HONEY!!!\p"
	.string "THOUGH YOUR DAD IS STILL MISSING\n"
	.string "MISSING, I BET THE CAKE WILL\p"
	.string "DELICIOUS!!!$"

MonitoringStation_Power_Text_Giovanni::
	.string "It's so dark in here…\p"
	.string "I must leave…\n"
	.string "before it swallows me…\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE NOW\p"
	.string "LEAVE NOW$"