MonitoringStation_Power_Text_Restore_Power::
	.string "Power has been restored.\p"
	.string "Emergency doors have been\n"
	.string "reopened.$"

MonitoringStation_Power_Text_Working::
	.string "The power in this base has\n"
	.string "been restored.$"
	
MonitoringStation_Power_Text_Rocket::
	.string "It's so dark in here…\p"
	.string "I must leave…\n"
	.string "before it swallows me…\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE NOW\p"
	.string "LEAVE NOW$"

MonitoringStation_Power_Text_Gym::
	.string "It's so dark in here…\p"
	.string "I must leave…\n"
	.string "before it swallows me…\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE NOW\p"
	.string "LEAVE NOW$"

MonitoringStation_Power_Text_Lance::
	.string "It's so dark in here…\p"
	.string "I must leave…\n"
	.string "before it swallows me…\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE NOW\p"
	.string "LEAVE NOW$"

MonitoringStation_Power_Text_Mom::
	.string "It's so dark in here…\p"
	.string "I must leave…\n"
	.string "before it swallows me…\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE NOW\p"
	.string "LEAVE NOW$"

MonitoringStation_Power_Text_Giovanni::
	.string "It's so dark in here…\p"
	.string "I must leave…\n"
	.string "before it swallows me…\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE\p"
	.string "I MUST LEAVE NOW\p"
	.string "LEAVE NOW$"